export const Data = [
  {
    question: "Why is Solar important?",
    answer:
      "Solar energy - a clean source No greenhouse gas emissions are released into the atmosphere when you use solar panels to create electricity. And because the sun provides more energy than we'll ever need, electricity from solar power is a very important energy source in the move to clean energy production.",
  },
  {
    question: "How long do solar panels last?",
    answer:
      <div><b>25 years. Yes a solar panel lasts for 25 years.</b><br/>
 The good news is that most residential solar panels should operate for 25 years before degradation (or reduced energy production) is noticeable. Even after that point, solar panels can continue to convert sunlight into solar energy—just at a less efficient rate than when they were new. </div>,
  },
  {
    question: "Where are solar energy used?",
    answer:
      "Solar energy is widely used in solar water heaters and home heating systems. Solar pond heat is used to produce chemicals, food, textiles, warm greenhouses, swimming pools, and livestock buildings. Solar energy can also be used for cooking and providing power to electronic devices. Solar energy is widely used in solar water heaters and home heating systems. Solar pond heat is used to produce chemicals, food, textiles, warm greenhouses, swimming pools, and livestock buildings. Solar energy can also be used for cooking and providing power to electronic devices. ",
  },
  {
    question: "Why is solar energy renewable?",
    answer:
      " Solar energy is the energy generated by the Sun's light (rooftop solar energy) and warmth (solar thermal energy) for the generation of electricity or heat. Solar energy is inexhaustible and renewable because it comes from the Sun. It is collected using panels and mirrors. ",
  },
  {
    question: "Why solar energy is the future?",
    answer:
      "Solar power is a critical future production method in the transition to clean energy, and as economies of scale drive down prices, its relevance will only grow. What are the benefits of solar energy? The biggest benefit is that it is a renewable, clean source of energy. Solar energy can also be scaled. ",
  },
  {
    question: "Do solar panels work in rain?",
    answer:
      " Some solar home systems are made to function whether it's bright, overcast, or even raining! ",
  },
  {
    question: "How solar will change the world?",
    answer:
      " In order to safeguard people, wildlife, and ecosystems, it is essential to reduce greenhouse gas emissions and mitigate climate change. Solar energy plays a significant part in these efforts as a sustainable energy source. Additionally, solar energy may minimize water consumption in energy generation and enhance air quality.",
  },
  {
    question: "What are 10 interesting facts about solar energy?",
    answer:
 
    <ol style={{"counter-reset": "list-number"}}>
    <li  style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Solar energy is the most abundant energy source on the planet.
The total annual energy consumption of everyone on the planet is equal to the amount of potential solar energy that falls on Earth's surface in one hour. 20 days of sunshine can generate the same amount of energy as all of the coal, oil, and natural gas on the planet combined.</li>
    <li  style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Solar power is the most rapidly expanding energy source.
Early in 2019, the United States surpassed 2 million solar system installations. This achievement comes only three years after the industry completed its one millionth installation, an accomplishment that took 40 years. The solar sector will surpass 4 million installations by 2023. Solar energy is the world's fastest expanding energy resource.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Solar energy is the world's most affordable source of energy.
Since 2008, the cost of solar panels has decreased by 80%. The cost of generating and installing new solar power generation fell to $1.65 per watt in December 2016, just edging out its renewable counterpart wind ($1.66/Watt) and its fossil fuel opponents.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Solar electricity has been around since 1839
In 1839, Alexandre Edmond Becquerel discovered the photovoltaic effect—that is, the ability to create an electric current from the sun’s rays. Then, Russell Ohl invented the first solar panel cell in 1941 and the first commercial panel was put out by Bell Laboratories in 1954.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Today, solar panel efficiency is higher than ever
Most solar panels sold in 2020 have efficiencies between 15% and 20%, according to the National Renewable Energy Laboratory (NREL). The first silicon solar panels were only about 6% efficient.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>The most efficient panels are made of monocrystalline silicon.
Monocrystalline solar panels are made from a single silicon crystal. They have a 5% higher efficiency than polycrystalline panels. This increased efficiency usually comes at a larger cost. However, because MOXIE obtains bulk purchasing discounts, we are able to provide monocrystalline panels at roughly the same price as polycrystalline panels.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Solar panels may generate electricity even when there is no direct sunshine.
Even if the sun isn't directly shining on the panels - or if it's a foggy day - the colors reflected from the sky are being caught and used by the solar panel cells to generate power. Still, the orientation of solar panels is important, and shading from trees and buildings should be considered before installation.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>An full house and more may be powered by solar energy.
The majority of solar panel systems on the market today are created to fit your daily energy demands, including those of air conditioners and other large appliances. For grid-tied systems, net metering makes sure you always have access to the energy you require. Additionally, you may upgrade your system with an energy storage battery to have a solar energy source for your own private backup needs.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Most homeowners reach the break-even threshold in less than ten years.
The break-even point, often called the "solar payoff phase," is significant. With your energy savings, you may offset the cost of your solar energy system. Your precise break-even point depends on a number of things, but considering that the majority of solar panels have a 25-year warranty, it's a reasonably secure investment.</li>
    <li style={{    "font-family": "Poppins",
    "font-style": "normal",
    "font-weight": 400,
    "font-size": "16px",
    "line-height": "30px",
    "padding": "1rem",
    "text-align": "center",
    "letter-spacing": "-0.5px",
    "color": "rgba(0,0,0,0.7)",}}>Solar panels are not necessary to purchase outright.
Even if you're unable to pay for the installation of a solar panel system entirely, you may still benefit from this wise purchase. Low-interest solar panel financing is available from MOXIE through partnerships with leading banks and lenders.</li>
    </ol>
    ,
  },
];
